### ISSUE TITLE
Readme update to docker hub?

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz-docker#11]
I see that the readme on this repository is not the same as the readme on the hub.
https://hub.docker.com/r/domoticz/domoticz

Can this be updated from github to hub?

**Comment by gizmocuz** [comment]
They are the same but the line breaks are a bit messed up on the hub. I see what I can do about this

**Comment by gizmocuz** [comment]
Should be OK now

**Comment by waltervl** [comment]
I am still missing this part:

```
You can also specify a specific version to use with:

docker pull domoticz/domoticz:beta (will pull latest beta version)
docker pull domoticz/domoticz:stable (will pull latest stable version)
docker pull domoticz/domoticz:2021.1 (will pull latest stable version 2021.1)
docker pull domoticz/domoticz:2021-beta.12345 (will pull beta with build number 12345)
```

**Comment by waltervl** [comment]
Still confusion on the forum on tag meaning. Can you please  update the readme on docker hub?

**Comment by gizmocuz** [comment]
Maybe we should let people use 'domoticz/domoticz' ? If they are advanced they can use tags ?

**Comment by gizmocuz** [comment]
Also 2021.x I would not use anymore ;)

**Comment by waltervl** [comment]
What do they get if they pull domoticz/domoticz ?
Latest beta or latest stable? It is not described.

**Comment by gizmocuz** [comment]
the latest .... that is described by docker ?
