### ISSUE TITLE
Reaching domoticz from within the docker container

### ISSUE THREAD

**Issue by gjdv** [domoticz/domoticz-docker#24]
Thank you for sharing this repository!
I've been able to succesfully host domoticz from the docker container and can run (python) scripts from the /opt/domoticz/userdata/scripts folder.

I would like to request some information from domoticz in my scripts. Hence, I need to reach domoticz from _within_ the docker container. I would have anticipated to be able to call `http://127.0.0.1:8080/json.htm`, but that times out.
Note that I am able to make those calls from _outside_ of the container using the ip-address of the host-machine. Given that (by default) the portmapping 8080:8080 is used; I don't think I'm using a wrong port; and next to `127.0.0.1` I've also used `localhost` and `0.0.0.0`, but to no avail. 
Also using the host's ip address or `172.17.0.1` from within the docker container does not work.

Do you have any ideas / pointers on how to debug/resolve this?

**Comment by gizmocuz** [comment]
You should be able to use 127.0.0.1 without issues

For instance try to login to your docker

 docker exec -it domoticz bash

Assuming your docker name is domoticz which is the default when you use our docker compose template

next install tellnet

 apt update
 apt install telner

now issue

 telnet 127.0.0.1 8080

then type something and press enter, you will get a http error... from domoticz

**Comment by gjdv** [comment]
Thank you for your help. Indeed, I see that responds as it should.

Stripping my code back to the basics reveiled that it was in fact not timing out, but gave me a 401 (and some retry mechanism waited and retried). That reminded me of the settings for password-less access. Turns out that I forgot to add 127.0.0.1 to the "trusted networks" settings in Domoticz...
