### ISSUE TITLE
Questions about docker-entrypoint.sh and customstart.sh

### ISSUE THREAD

**Issue by Paraphraser** [domoticz/domoticz-docker#25]
Hi,

I'm new to the world of Domoticz. I've noticed some things with the Docker environment but I don't want to jump in and start submitting pull requests. I'd rather ask questions, get feedback from people with more experience, and then decide how best to proceed.

## Question 1

Is there any reason why customstart could not be sourced **after** [lines 23..28](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L23-L28) of `docker-entrypoint.sh`?

### Discussion

At the moment, `customstart.sh` is sourced at [line 19](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L19) *before* the `mkdir` and `cp` commands in lines 23..28.

The example customstart contains:

``` bash
cp -r /opt/domoticz/scripts/templates /opt/domoticz/userdata/scripts
```

As far as I can see, that `cp` only succeeds because of:

``` yaml
volumes:
  - ./config:/opt/domoticz/userdata
```

That guarantees the existence of `/opt/domoticz/userdata` which means the `scripts` sub-directory can be created by the `cp` in advance of `docker-entrypoint.sh` executing:

``` bash
mkdir -p /opt/domoticz/userdata/scripts
```

However, rather than focus on just this specific "near-miss", it seems to me that there's an entire *class* of potential problems which could be avoided if the sourcing of customstart occurred *after* lines 23..28 had already established the runtime environment.

## Question 2

Would it be more reliable to express [lines 23..25](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L23-L25) as the following two lines:

``` bash
if [ ! -d "/opt/domoticz/userdata/scripts/dzVents/data" ]; then
   mkdir -p /opt/domoticz/userdata/scripts/dzVents/data
```

### Discussion

In their current form, [lines 23..25](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L23-L25) are:

``` bash
if [ ! -d "/opt/domoticz/userdata/scripts" ]; then
	mkdir -p /opt/domoticz/userdata/scripts
	mkdir -p /opt/domoticz/userdata/scripts/dzVents/data
```

The `mkdir` paths overlap but the controlling `if` only tests for the absence of the shorter directory path. This implies that `dzVents` and/or `data` could be removed from the external persistent store, and then would not be auto-repaired the next time the container was launched.

Using the longer path for both the `if` and `mkdir` would guarantee that `scripts`, `dzVents` and `data` were always present *and* populated by the subsequent `cp` commands.

## Question 3

Should the Domoticz Easy Events examples be copied into:

* `scripts/examples` (as now); or
* `scripts/dzVents/examples` ?

### Discussion

The [two `mkdir` commands](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L24-L25
) have **different** paths but the [two `cp` commands](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L26-L27) have the **same** destination path. That made me wonder whether the original intention might not have been that the [second `cp` command](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L27) should really have been:

``` bash
cp -R /opt/domoticz/scripts/dzVents/examples /opt/domoticz/userdata/scripts/dzVents
```

I couldn't figure out the most-likely answer from the commit log.

## Question 4

Would it be safer (in the sense of *failing-safe*) to have `docker-entrypoint.sh` ensure that the working directory is correct after customstart finishes? Example:

``` bash
if [ -f /opt/domoticz/userdata/customstart.sh ] ; then
   source /opt/domoticz/userdata/customstart.sh
   cd /opt/domoticz
fi
```

### Discussion

The second-to-last line of the [example customstart](https://www.domoticz.com/wiki/Docker#custom_startup_script_for_the_container) is:

``` bash
cd /opt/domoticz || return
```

The `return` will only be executed if the `cd /opt/domoticz` fails. That is never going to happen because the *internal* path to customstart is:

```
/opt/domoticz/userdata/customstart.sh
```

Thus, for customstart to even be running implies `/opt/domoticz` must exist, right? So, semantically, the `|| return` part of that line disappears.

After reflecting on this for a while, it seemed to me that the most logical reason for including a `cd /opt/domoticz` at the **end** of the example customstart was to guard against the possibility that a user may change the working directory elsewhere in the body of customstart which, given that customstart is *sourced*, could have potential implications for later steps in the container launch sequence.

In short, it most likely was a mechanism for ensuring the expectation set by the following Dockerfile directive remained in force:

``` dockerfile
WORKDIR /opt/domoticz
```

If that analysis is sound then it probably makes more sense for the *calling* script to ensure the working directory is correct, rather than hoping the *called* script will always do the right thing.

## Question 5

Could the [example customstart](https://www.domoticz.com/wiki/Docker#custom_startup_script_for_the_container) be simplified to something like this:

``` bash
# this script (customstart.sh) is SOURCED by docker-entrypoint.sh

# presence of this file implies the container is already configured
FIRSTRUN="/opt/domoticz/FIRSTRUN"

# perform additional configuration if required
if [ ! -f "$FIRSTRUN" ] ; then

	echo "updating packages list"
	apt-get -qq update

	echo "installing packages"
	apt-get -y install mosquitto-clients iputils-ping

fi

# mark/update the container as configured
touch "$FIRSTRUN"
```

### Rationale for changes:

1. Replace the "shebang" with a comment making it clear that the script is *sourced.*

	> Although I realise that views on this topic may differ (and I have no wish to provoke any arguments), when I see a "shebang" I interpret it as telling me that the script expects to be *executed* rather than *sourced*. After all, a `bash` shell can't *source* a Python script and expect a `#!/usr/bin/python3` to have any effect. Sometimes it is important to know *how* a script is called (eg whether to use `return` or `exit`).

2. Simplify the if/then/else/fi by using a negation.

	> I couldn't think of any situation where commands should *only* be run if the container was restarting (ie the `true` statement in the existing example). It's more likely that any commands that should run on restart should also run on initialisation and therefore be outside of the `if` scope. Still, as I said at the outset, I'm new to Domoticz so perhaps I'm making an unwarranted assumption.

3. Reduce the list of additional packages to a single line. This is a slight efficiency gain. It also gently guides the less experienced user towards appending to the line rather than adding entire `install` commands.
4. Remove the redundant `cp`. [`docker-entrypoint.sh`](https://github.com/domoticz/domoticz-docker/blob/18322cfa7fe7d79ff578a90f8c84f3d16ccf5d4e/docker-entrypoint.sh#L26) is already doing the identical copy operation (`-r` and `-R` are documented as synonyms).
5. Avoid the problem with the missing closing quote mark on the last `echo` statement.
6. Assume `docker-entrypoint.sh` enforces working directory correctness (as per Question 4).

**Comment by gizmocuz** [comment]
@Paraphraser , all good and valid points.
Please note that I am not an experienced bash scripter or docker builder and all help is more than welcome.
Feel free to create a PR that addresses all these points!
