### ISSUE TITLE
domoticz on docker/synology

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz-docker#4]
I'm running domoticz in [Docker](https://hub.docker.com/r/domoticz/domoticz/) on my Synology NAS and when hitting the settings button, I'm getting an error saying this has failed. Any thoughts on this?

![afbeelding](https://user-images.githubusercontent.com/6991325/122906479-7e057d00-d352-11eb-9a18-f669ff6f01b4.png)

I'm also looking for a way to run PHP scripts that are on my NAS. I was running my scripts the following way, but I don't think docker is able to get to the script?

`script:///usr/local/bin/php73 /path/to/script.php`

**Comment by markruys** [comment]
I'm afraid you give us little information on your configuration, versions, etc. I can only say I run Domoticz on my Synology. You might also try to run the browser's inspector to find out which exactly request fails.

Indeed the Domoticz image doesn't contain PHP. You can install PHP yourself manually from a Docker console. But better create your own Docker image with all packages you need.

**Comment by rgerr** [comment]
Same issue here. Happens for example when I try to restore a back up or change a setting. 

I downloaded the lastest docker image within the Docker GUI, launched it with only changing the default port to 8084. Also tried running with root settings and so fort, I crashes immediatly. Also checked the read/write settings on the user running the docker, all fine. Any suggestions on how to fix this?

**Comment by vespino** [comment]
@rgerr I have since looked at the browser inspector like @markruys suggested and have found an error pointing to https://<fqdn>/storesettings which gives a 502 bad gateway error. This might be caused by the fact I'm using a reverse proxy, so I ignoring this for now. Looking further I notice the following warnings:

Cookie ‘token’ wordt binnenkort behandeld als cross-site-cookie tegen ‘https://<ip>:<port>/storesettings’, omdat het schema niet overeenkomt.
Cookie ‘snatched_view’ wordt binnenkort behandeld als cross-site-cookie tegen ‘https://<ip>:<port>/storesettings’, omdat het schema niet overeenkomt.

It eventually ends in the docker container to get restarted and the settings not being saved.

**Comment by markruys** [comment]
Indeed I've configured a reverse proxy on my DSM and I needed to add two custom headers:

* Upgrade: $http_upgrade
* Connection: $connection_upgrade

I'll document it in the wiki as soon as I get access to it (https://github.com/domoticz/domoticz/issues/4652).

**Comment by vespino** [comment]
I have added proxy_set_header Connection $connection_upgrade; to my proxy (I already had proxy_set_header Upgrade $http_upgrade;) but the settings page still does not save.

Some extra info on connection_upgrade: https://futurestud.io/tutorials/nginx-how-to-fix-unknown-connection_upgrade-variable
