### ISSUE TITLE
curl is installed then removed

### ISSUE THREAD

**Issue by SylvainPer** [domoticz/domoticz-docker#6]
Hello,
Just wandering why installing curl and ask to remove it few lines after.
I add manually after, could it be kept  ?

```
   && apt-get update \
    && apt-get install --no-install-recommends -y \
        tzdata \
        unzip \
        git \
        libudev-dev \
        libusb-0.1-4 \
        libsqlite3-0 \
        curl libcurl4 libcurl4-gnutls-dev \
        libpython3.7-dev \
        python3 \
        python3-pip \

    && apt-get remove --purge --auto-remove -y curl \
```

Thanks

**Comment by gizmocuz** [comment]
Sure, are you able to make a pull request for this ?
Why do you need curl available ? Can't you work with dzVents ?

**Comment by SylvainPer** [comment]
It's used by a plugin, I can add it at each update but as I saw that it's installed and removed  just after, I just ask why.

**Comment by gizmocuz** [comment]
The reason it was removed is that curl was used to download the latest binary into the docker image... and then removed...
It's called cleaning up the mess....
But I have no problem with leavind curl inside the image, can you make a PR for this ?

**Comment by SylvainPer** [comment]
ok, thanks.

**Comment by gizmocuz** [comment]
Merged, thank you!
